name: sample_demo(date:yyyyMMdd)$(Rev:r)
trigger:
 - Main
pool:
 name: Default
steps:
 - task: VSBuild@1
   inputs:
     solution: '**\*.sln'
     msbuildArgs: '''/p:DeployOnBuild=true /p:WebPublishMethod=Package   /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'''
